import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
const read=(p:string)=>JSON.parse(readFileSync(resolve("public/data/aggregation-stability",p),"utf8"));
const id="p-feba1dc1f7ef",pair=read("pairs/fe.json")[id];
const typewise=(id:string)=>JSON.parse(readFileSync(resolve(`public/data/typewise-matched-aggregation/pairs/${id.slice(2,4)}.json`),"utf8")).pairs[id];

test("opens base and partner controls while retaining the exact raw scores",async({page},testInfo)=>{
  const requests:string[]=[],errors:string[]=[];
  page.on("request",r=>requests.push(r.url()));page.on("pageerror",e=>errors.push(e.message));
  await page.goto("/?cc_stability=original#complementarity");
  const section=page.locator("#complementarity");
  await expect(section.getByTestId("ad-effect")).toContainText("0.56%");
  expect(requests.some(u=>u.includes("/aggregation-decision-pairs/"))).toBe(false);
  await section.getByRole("button",{name:"One model pair",exact:true}).click();
  await section.getByLabel("Base model",{exact:true}).selectOption(pair.model_a);
  await section.getByLabel("Partner model",{exact:true}).selectOption(id);
  await expect(section.getByTestId("ad-pair-identities")).toHaveCount(0);
  await expect(section.getByTestId("ad-pair-effect")).toHaveCount(0);
  await expect(section.getByTestId("ad-pair-facts")).toHaveCount(0);
  await expect(section.getByTestId("ad-effect")).toHaveCount(0);
  const table=section.getByTestId("ad-pair-main-table");
  for(const m of [0,1,2,3,4])await expect(table).toContainText(pair.scopes.complementary.brier[m].toFixed(6));
  await expect(table).toContainText(pair.scopes.complementary.pools.raw.brier[7].toFixed(6));
  const eventType=typewise(id).scopes.complementary;
  await expect(table.getByTestId("ad-event-type-joint-brier")).toHaveText(eventType.brier[2].toFixed(6));
  await expect(table.getByTestId("ad-event-type-joint-ece")).toHaveText(eventType.ece[2].toFixed(6));
  await expect(table.locator("tbody tr").nth(5)).toHaveAttribute("data-testid","ad-uncalibrated-joint-row");
  await expect(table.locator("tbody tr").nth(6)).toHaveAttribute("data-testid","ad-event-type-joint-row");
  await expect(table.getByTestId("ad-event-type-joint-row").locator(".ad-row-number")).toHaveText("4");
  const routes=pair.routes.filter((route:{complementary:boolean})=>route.complementary);
  const firstType=routes[0],firstScores=typewise(id).event_types[firstType.type];
  const performance=section.getByTestId("ad-event-type-performance");
  await expect(section.getByTestId("ad-complementary-type").first()).toHaveAttribute("aria-pressed","true");
  await expect(performance.getByRole("heading",{name:/Finance \/ economics/})).toBeVisible();
  await expect(performance.getByTestId("ad-event-type-base-row").locator("td").first()).toHaveText(firstScores.brier[0].toFixed(6));
  await expect(performance.getByTestId("ad-event-type-partner-row").locator("td").first()).toHaveText(firstScores.brier[1].toFixed(6));
  await expect(performance.getByTestId("ad-event-type-global-row")).toContainText(firstScores.brier[2].toFixed(6));
  await expect(performance.getByTestId("ad-event-type-global-row")).toContainText(firstScores.ece[2].toFixed(6));
  await expect(performance.getByTestId("ad-event-type-weight-row")).toContainText(firstScores.brier[3].toFixed(6));
  await expect(performance.getByTestId("ad-event-type-weight-row")).toContainText(firstScores.ece[3].toFixed(6));
  const secondType=routes[1],secondScores=typewise(id).event_types[secondType.type];
  await section.getByRole("button",{name:new RegExp(`^${secondType.type[0].toUpperCase()}${secondType.type.slice(1)}`)}).click();
  await expect(performance.getByTestId("ad-event-type-base-row").locator("td").first()).toHaveText(secondScores.brier[0].toFixed(6));
  await expect(performance.getByTestId("ad-event-type-weight-row")).toContainText(secondScores.ece[3].toFixed(6));
  await expect(section.getByRole("button",{name:"2–4 models",exact:true})).toHaveCount(0);
  await expect(page).toHaveURL(new RegExp(`cc_pair=${id}`));
  await expect(section.locator("details[open]")).toHaveCount(0);
  await expect(section.locator(".ad-verdict,.ad-comparison-note,.ad-footnote,.ad-reading")).toHaveCount(0);
  await page.screenshot({path:testInfo.outputPath("base-partner-picker.png")});
  await expect(section.getByTestId("ad-test-scope-label")).toHaveCount(0);
  await expect(section.getByTestId("ad-cohort-label")).toHaveCount(0);
  await expect(section.getByTestId("ad-context")).toHaveCount(0);
  await expect(section.getByText("Pooling methods",{exact:true})).toHaveCount(0);
  await expect(section.locator("[data-testid=ad-pair-results] > .ad-pair-context")).toHaveCount(0);
  await expect(section.getByTestId("ad-stability-status")).toHaveCount(0);
  await expect(section.locator(".ad-pair-browse")).not.toContainText("eligible partners");
  await page.reload();await expect(table).toContainText(pair.scopes.complementary.pools.raw.brier[7].toFixed(6));
  expect(requests.some(u=>u.endsWith("primary-pair-diagnostics.json.gz")||u.includes("/complementarity/study.json"))).toBe(false);
  const width=await page.evaluate(()=>[document.documentElement.scrollWidth,document.documentElement.clientWidth]);
  expect(width[0]).toBeLessThanOrEqual(width[1]+1);expect(errors).toEqual([]);
});

test("pins the base while browsing partners and orients both sides correctly",async({page})=>{
  await page.goto(`/?cc_stability=original&cc_result=pair&cc_pair=${id}#complementarity`);
  const section=page.locator("#complementarity");
  await expect(section.getByTestId("ad-pair-results")).toBeVisible();
  await section.getByRole("button",{name:"Next partner →",exact:true}).click();
  const next=await section.getByLabel("Partner model",{exact:true}).inputValue();expect(next).not.toBe(id);
  await expect(section.getByLabel("Base model",{exact:true})).toHaveValue(pair.model_a);
  const nextPair=read(`pairs/${next.slice(2,4)}.json`)[next];
  await expect(section.getByTestId("ad-event-type-joint-brier")).toHaveText(typewise(next).scopes.complementary.brier[2].toFixed(6));
  await expect(section.getByTestId("ad-event-type-joint-ece")).toHaveText(typewise(next).scopes.complementary.ece[2].toFixed(6));
  await expect(section.getByLabel("Partner model",{exact:true}).locator("option:checked")).toHaveText(nextPair.model_a===pair.model_a?nextPair.model_b:nextPair.model_a);
  await section.getByLabel("Base model",{exact:true}).selectOption(pair.model_b);
  await section.getByLabel("Partner model",{exact:true}).selectOption(id);
  await expect(section.getByLabel("Base model",{exact:true})).toHaveValue(pair.model_b);
  const firstComplementary=pair.routes.find((route:{complementary:boolean})=>route.complementary)!,firstScores=typewise(id).event_types[firstComplementary.type];
  await expect(section.getByTestId("ad-event-type-base-row").locator("td").first()).toHaveText(firstScores.brier[1].toFixed(6));
  await expect(section.getByTestId("ad-event-type-partner-row").locator("td").first()).toHaveText(firstScores.brier[0].toFixed(6));
  await section.getByText("Event-type selections",{exact:true}).click();
  const first=section.getByTestId("ad-pair-routes").locator("tbody tr").first();
  await expect(first.locator("td").nth(1)).toHaveText(pair.routes[0].train_brier_b.toFixed(5));
  await expect(first.locator("td").nth(3)).toHaveText(pair.routes[0].selected===1?"Base":"Partner");
  await expect(section.getByTestId("ad-pair-main-table")).toContainText(pair.scopes.complementary.pools.raw.brier[7].toFixed(6));
  await expect(section.getByTestId("ad-event-type-joint-brier")).toHaveText(typewise(id).scopes.complementary.brier[2].toFixed(6));
  await section.getByRole("button",{name:"Overall evidence",exact:true}).click();
  await expect(section.getByTestId("ad-effect")).toContainText("0.56%");
});

test("pair view omits pooling methods while retaining event-type evidence",async({page})=>{
  await page.goto(`/?cc_stability=original&cc_result=pair&cc_pair=${id}#complementarity`);
  const section=page.locator("#complementarity");
  await expect(section.getByText("Pooling methods",{exact:true})).toHaveCount(0);
  await expect(section.getByTestId("ad-pair-pool-table")).toHaveCount(0);
  await expect(section.getByText("Test directions",{exact:true})).toHaveCount(0);
  await expect(section.getByTestId("ad-pair-directions")).toHaveCount(0);
  await section.getByText("Event-type selections",{exact:true}).click();
  await expect(section.getByTestId("ad-pair-routes").locator("tbody tr")).toHaveCount(pair.routes.length);
  const width=await page.evaluate(()=>[document.documentElement.scrollWidth,document.documentElement.clientWidth]);expect(width[0]).toBeLessThanOrEqual(width[1]+1);
});

test("pair data failure supports retry without stale scores",async({page})=>{
  let fail=true;
  await page.route("**/aggregation-stability/pairs/fe.json",async route=>{if(fail)await route.fulfill({status:503,body:"Unavailable"});else await route.continue();});
  await page.goto(`/?cc_stability=original&cc_result=pair&cc_pair=${id}#complementarity`);
  const section=page.locator("#complementarity");
  await expect(section.getByRole("alert")).toContainText("503");
  await expect(section.getByTestId("ad-pair-results")).toHaveCount(0);
  fail=false;await section.getByRole("button",{name:"Retry selected pair",exact:true}).click();
  await expect(section.getByTestId("ad-pair-main-table")).toContainText(pair.scopes.complementary.pools.raw.brier[7].toFixed(6));
});
