import {useEffect,useMemo,useState} from "react";
import {score} from "../lib/complementarity";
import type {DecisionFilters,PoolMode} from "../lib/aggregationDecision";
import {DECISION_PAIR_PATH,loadDecisionPairIndex,loadDecisionPair,pairEligible,searchDecisionPairs,pairDecisionSummary,type DecisionPairIndex,type DecisionPair} from "../lib/aggregationDecisionPairs";

const pct=(v:number|null,digits=1)=>v==null?"—":`${(100*v).toFixed(digits)}%`;
const color=(v:number)=>v>1e-10?"ad-positive":v< -1e-10?"ad-negative":"";
const labels=[
  ["Choose the historical type winner","Use its original probability."],
  ["Calibrate that selected forecast","Add a global probability calibration curve."],
  ["Strengthen the single-forecast baseline","Add event-type adjustments and flexible calibration."],
  ["Add the other model’s forecast","Use the same calibration structure with one extra predictor."],
];
const typeNames:Record<string,string>={health:"Health",politics:"Politics",sports:"Sports",finance:"Finance / economics",technology:"Technology",climate_weather:"Climate / weather",entertainment_culture:"Entertainment / culture"};

function PairEvidence({pair,index,filters}:{pair:DecisionPair;index:DecisionPairIndex;filters:DecisionFilters}){
  const [mode,setMode]=useState<PoolMode>("raw");
  const s=pairDecisionSummary(pair,filters),r=s.row,pool=r.pools[mode];
  const positive=s.gain>1e-10,negative=s.gain< -1e-10;
  const title=positive?"Aggregation improves this pair.":negative?"Aggregation is worse for this pair.":"No measured gain for this pair.";
  const poolWins=[2,3,4,5,6,7,8,9].filter(m=>r.brier[6]-pool.brier[m]>1e-10).length;
  return <div data-testid="ad-pair-results">
    <div className="ad-pair-identities" data-testid="ad-pair-identities"><div><span>MODEL A</span><b>{pair.model_a}</b></div><div><span>MODEL B</span><b>{pair.model_b}</b></div></div>
    <p className="ad-pair-context">Primary split {index.primary_split} · {index.primary_fold===0?"A → B":"B → A"} · Pair {pair.id} · Train BI gap {score(pair.train_gap,2)} · {pct(pair.train_coverage)} type coverage</p>
    <section className="ad-verdict"><div><p className="ad-eyebrow">THIS PAIR / MATCHED COMPARISON</p><h2 data-testid="ad-pair-title">{title}</h2><p>The strong selected-forecast baseline has Brier {score(r.brier[6],6)}. Adding the other forecast changes it to {score(r.brier[7],6)} on the same {r.events} test events.</p><p className="ad-verdict-limit">This is one pair’s held-out result. It does not replace the overall evidence or establish a cost benefit.</p></div><div className={`ad-effect ${color(s.gain)}`} data-testid="ad-pair-effect"><strong>{pct(s.relative==null?null:Math.abs(s.relative),2)}</strong><span>relative Brier {negative?"increase":"reduction"}</span><small>vs this pair’s strong single-forecast baseline</small></div></section>
    <div className="ad-facts" data-testid="ad-pair-facts"><div><strong className={color(s.gain)}>{score(s.gain,6,true)}</strong><span>absolute Brier improvement</span></div><div><strong>{r.events.toLocaleString()}</strong><span>test events · {r.targets.toLocaleString()} targets</span></div><div><strong>{s.positive}/{s.directions.length}</strong><span>eligible directions improve</span></div></div>
    <section className="ad-comparison"><div className="ad-section-heading"><div><p className="ad-eyebrow">SAME FOUR STEPS / THIS PAIR ONLY</p><h2>How much does aggregation add?</h2></div><span>Brier score ↓ · {filters.scope==="all"?"All test events":"Complementary events"}</span></div>
      <div className="ad-table-scroll"><table className="ad-main-table" data-testid="ad-pair-main-table"><caption>Same model pair, type router and test events in all four rows.</caption><thead><tr><th>Prediction pipeline</th><th>Forecasts used per event</th><th>Test Brier ↓</th></tr></thead><tbody>{[0,5,6,7].map((m,k)=><tr key={m} className={k===2?"ad-single-row":k===3?"ad-joint-row":""}><th scope="row"><div className="ad-pipeline-label"><span className="ad-row-number">{k+1}</span><div><b>{labels[k][0]}</b><small>{labels[k][1]}</small>{k===2&&<em>Strong single-forecast baseline</em>}{k===3&&<em>Matched aggregation</em>}</div></div></th><td>{k===3?"2 forecasts":"1 selected forecast"}</td><td>{score(r.brier[m],6)}</td></tr>)}</tbody></table></div>
      <p className="ad-comparison-note">The key comparison is <b>row 3 → row 4</b>. Adding the other forecast {positive?"lowers":negative?"raises":"does not change"} this pair’s Brier{Math.abs(s.gain)>1e-10?` by ${score(Math.abs(s.gain),6)}`:""}.</p>
      <p className="ad-footnote">Both matched pipelines fit the same calibration family and regularization on training events. The joint model adds the other forecast as a predictor. “1 selected forecast” can come from different models across event types.</p>
    </section>
    <div className="ad-supporting"><p className="ad-eyebrow">SUPPORTING EVIDENCE / THIS PAIR ONLY</p>
      <details className="ad-disclosure"><summary>Compare pooling methods for this pair</summary><div className="ad-detail-body">
        <div className="ad-switch ad-pool-switch" role="group" aria-label="Pair pooling pipeline">{([['raw','No calibration'],['input','Calibrate models → pool'],['output','Pool → calibrate output']] as const).map(([v,label])=><button key={v} aria-pressed={mode===v} onClick={()=>setMode(v)}>{label}</button>)}</div>
        <p data-testid="ad-pair-pool-finding" className="ad-pool-finding"><b>{poolWins}/8 pooling methods</b> beat this pair’s strong single-forecast baseline in the selected test scope.</p>
        <div className="ad-table-scroll"><table className="ad-pool-table" data-testid="ad-pair-pool-table"><caption>Positive gain means lower Brier. Every method uses this pair’s same test events.</caption><thead><tr><th>Method</th><th>Brier ↓</th><th>Gain vs this pipeline’s selection</th><th>Gain vs strong single baseline</th></tr></thead><tbody>{[2,3,4,5,6,7,8,9].map(m=><tr key={m}><th scope="row">{index.pool_labels[m]}</th><td>{score(pool.brier[m],6)}</td><td className={color(pool.brier[0]-pool.brier[m])}>{score(pool.brier[0]-pool.brier[m],6,true)}</td><td className={color(r.brier[6]-pool.brier[m])}>{score(r.brier[6]-pool.brier[m],6,true)}</td></tr>)}</tbody></table></div>
        <p className="ad-footnote">This pipeline’s selection Brier: {score(pool.brier[0],6)}. Strong single-forecast Brier: {score(r.brier[6],6)}. These complete pipelines use simpler calibration than the matched joint comparison above.</p>
      </div></details>
      <details className="ad-disclosure"><summary>Check this pair across test directions</summary><div className="ad-detail-body"><div className="ad-table-scroll"><table className="ad-direction-table" data-testid="ad-pair-directions"><caption>Only directions in which this pair meets the current training filters.</caption><thead><tr><th>Split / train → test</th><th>Events</th><th>Strong single Brier</th><th>Joint Brier</th><th>Improvement</th></tr></thead><tbody>{s.directions.map(d=>{const ds=d.scopes[filters.scope],g=ds.brier[2]!-ds.brier[3]!;return <tr key={`${d.split}-${d.fold}`}><th scope="row">{d.split} · {d.fold===0?"A → B":"B → A"}{d.split===index.primary_split&&d.fold===index.primary_fold?" · primary":""}</th><td>{ds.events}</td><td>{score(ds.brier[2],6)}</td><td>{score(ds.brier[3],6)}</td><td className={color(g)}>{score(g,6,true)}</td></tr>;})}</tbody></table></div><p className="ad-footnote">{s.directions.length} of 10 fixed directions are eligible for this pair under the current filters. Each direction uses its own training gap and coverage. Shared events make these stability checks, not independent replications.</p></div></details>
      <details className="ad-disclosure"><summary>Which event types choose each model?</summary><div className="ad-detail-body"><p>Historical training Brier determines the selected model. A complementary type has supported training advantage; fallback types use the Overall training winner.</p><div className="ad-table-scroll"><table className="ad-direction-table" data-testid="ad-pair-routes"><thead><tr><th>Event type</th><th>Train events</th><th>Model A Brier</th><th>Model B Brier</th><th>Selected model</th><th>Type support</th></tr></thead><tbody>{pair.routes.map(t=><tr key={t.type}><th scope="row">{typeNames[t.type]??t.type}</th><td>{t.train_events}</td><td>{score(t.train_brier_a,5)}</td><td>{score(t.train_brier_b,5)}</td><td>Model {t.selected===0?"A":"B"}</td><td>{t.fallback?"Overall fallback":t.complementary?"Complementary":"Other supported type"}</td></tr>)}</tbody></table></div><p className="ad-footnote">Original single-model test Brier in this scope: Model A {score(r.single_brier[0],6)}; Model B {score(r.single_brier[1],6)}. The four-row comparison uses the type-selected forecast as its starting point.</p></div></details>
      <details className="ad-disclosure"><summary>Calibration and this pair’s downloadable scores</summary><div className="ad-detail-body"><div className="ad-table-scroll"><table className="ad-ece-table"><thead><tr><th>Pipeline</th><th>ECE ↓</th></tr></thead><tbody>{[0,5,6,7].map((m,k)=><tr key={m}><th scope="row">{labels[k][0]}</th><td>{score(r.ece[m],6)}</td></tr>)}</tbody></table></div><p>Brier weights events equally, after averaging targets within each event. ECE uses ten equal-width bins with target weights. All displayed values come from the existing published experiments.</p><div className="ad-downloads"><button className="ad-link-button" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(pair,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`${pair.id}-aggregation.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download this pair’s scores ↓</button><a href={`${DECISION_PAIR_PATH}provenance.json`}>Data provenance ↗</a></div></div></details>
    </div>
  </div>;
}

export default function AggregationPairDecision({filters}:{filters:DecisionFilters}){
  const [index,setIndex]=useState<DecisionPairIndex|null>(null),[pair,setPair]=useState<DecisionPair|null>(null);
  const [error,setError]=useState(""),[pairError,setPairError]=useState(""),[attempt,setAttempt]=useState(0),[pairAttempt,setPairAttempt]=useState(0);
  const [selected,setSelected]=useState(()=>new URLSearchParams(location.search).get("cc_pair")??"");
  const [query,setQuery]=useState("");
  useEffect(()=>{const c=new AbortController();setError("");loadDecisionPairIndex(c.signal).then(v=>{if(!c.signal.aborted)setIndex(v);}).catch(e=>{if(!c.signal.aborted)setError(String(e.message??e));});return()=>c.abort();},[attempt]);
  useEffect(()=>{const onPop=()=>setSelected(new URLSearchParams(location.search).get("cc_pair")??"");window.addEventListener("popstate",onPop);return()=>window.removeEventListener("popstate",onPop);},[]);
  const eligible=useMemo(()=>index?.pairs.filter(p=>pairEligible(p,filters))??[],[index,filters.gap,filters.coverage,filters.pairScope]);
  const matches=useMemo(()=>searchDecisionPairs(eligible,query),[eligible,query]);
  const meta=eligible.find(p=>p.id===selected),position=matches.findIndex(p=>p.id===selected);
  function choose(id:string){setSelected(id);const q=new URLSearchParams(location.search);q.set("cc_pair",id);q.set("cc_result","pair");history.replaceState(null,"",`${location.pathname}?${q}#complementarity`);}
  useEffect(()=>{if(!selected&&eligible.length)choose(eligible[0].id);},[selected,eligible]);
  useEffect(()=>{setPair(null);setPairError("");if(!meta||!index)return;const c=new AbortController();loadDecisionPair(meta,index,c.signal).then(p=>{if(!c.signal.aborted)setPair(p);}).catch(e=>{if(!c.signal.aborted)setPairError(String(e.message??e));});return()=>c.abort();},[meta,index,pairAttempt]);
  if(!index)return <div className="ad-pending" role={error?"alert":"status"}>{error||"Loading the model-pair list…"}{error&&<button className="ad-link-button" onClick={()=>setAttempt(v=>v+1)}>Retry pair list</button>}</div>;
  return <section className="ad-pair-view" aria-label="Individual model-pair results">
    <div className="ad-pair-picker"><label>Search models<input aria-label="Search model pairs" type="search" value={query} placeholder="e.g. GPT-5 Claude" onChange={e=>setQuery(e.target.value)}/></label><label>Model pair<select aria-label="Verdict model pair" value={meta?.id??""} onChange={e=>choose(e.target.value)}><option value="" disabled>Choose an eligible pair</option>{meta&&!matches.some(p=>p.id===selected)&&<option value={meta.id}>{meta.model_a} × {meta.model_b} · current selection</option>}{matches.map(p=><option key={p.id} value={p.id}>{p.model_a} × {p.model_b}</option>)}</select></label></div>
    <div className="ad-pair-browse"><span>{matches.length.toLocaleString()} matching / {eligible.length.toLocaleString()} eligible pairs · alphabetical order</span><div><button onClick={()=>choose(matches[position-1].id)} disabled={position<=0}>← Previous pair</button><span>{position>=0?`${position+1} / ${matches.length}`:"—"}</span><button onClick={()=>choose(matches[position+1].id)} disabled={position<0||position>=matches.length-1}>Next pair →</button></div></div>
    {!meta?<p role="status" className="ad-pending">{eligible.length?"The selected pair is not eligible for the current training filters. Choose a pair from the list, or change the study scope.":"No pairs meet these training filters."}</p>:!pair||pair.id!==meta.id?<div className="ad-pending" role={pairError?"alert":"status"}>{pairError||"Loading this pair’s published results…"}{pairError&&<button className="ad-link-button" onClick={()=>setPairAttempt(v=>v+1)}>Retry selected pair</button>}</div>:<PairEvidence key={pair.id} pair={pair} index={index} filters={filters}/>}
  </section>;
}
